### ISSUE TITLE
With other non-aws plugins, this plugin errors on deleted machines

### ISSUE THREAD

**Issue by johnalotoski** [nix-community/nixops-encrypted-links#2]
When this plugin is packaged in a nixops with multiple plugins in addition to nixops-aws, such as nixops-packet, it causes an error to be thrown when it encounters a deleted machine.

Example:
* Spin up two packet (now equinix) machines
* nixops destroy one machine (machineDemo2)
* Then try to deploy machineDemo (with or without `--include machineDemo`) and a `defn was None` error is thrown due to machineDemo2 having a `'defn': None`
* Some debug statements included below:

```
nixops deploy

...

machineDemo.> waiting for SSH....
building all machine configurations...

Physical Spec of Encrypted Links = <nixops.deployment.Deployment object at 0x7f45dc69a0d0>

Doing machine: {'_wait_for': [], 'depl': <nixops.deployment.Deployment object at 0x7f45dc69a0d0>, 'name': 'machineDemo', 'id': 1163, 'logger': <nixops.logger.MachineLogger object at 0x7f45d95bce50>, 'defn': <nixops_packet.backends.device.PacketDefinition object at 0x7f45d955aa00>, '_ssh_pinged_this_time': True, 'ssh': <nixops.ssh_util.SSH object at 0x7f45d95bcfd0>, '_ssh_private_key_file': '/run/user/1001/nix-shell.c6au9U/nixops-tmp6yubpink/id_nixops-machineDemo', 'new_toplevel': None, '_conn': <packet.Manager.Manager object at 0x7f45d9522310>, '_created_event': <threading.Event object at 0x7f45d95700a0>, '_errored': False}

Getting encrypted links defn of: {'_wait_for': [], 'depl': <nixops.deployment.Deployment object at 0x7f45dc69a0d0>, 'name': 'machineDemo', 'id': 1163, 'logger': <nixops.logger.MachineLogger object at 0x7f45d95bce50>, 'defn': <nixops_packet.backends.device.PacketDefinition object at 0x7f45d955aa00>, '_ssh_pinged_this_time': True, 'ssh': <nixops.ssh_util.SSH object at 0x7f45d95bcfd0>, '_ssh_private_key_file': '/run/user/1001/nix-shell.c6au9U/nixops-tmp6yubpink/id_nixops-machineDemo', 'new_toplevel': None, '_conn': <packet.Manager.Manager object at 0x7f45d9522310>, '_created_event': <threading.Event object at 0x7f45d95700a0>, '_errored': False}

Doing machine: {'_wait_for': [], 'depl': <nixops.deployment.Deployment object at 0x7f45dc69a0d0>, 'name': 'machineDemo2', 'id': 1168, 'logger': <nixops.logger.MachineLogger object at 0x7f45d95bc6d0>, 'defn': None, '_ssh_pinged_this_time': False, 'ssh': <nixops.ssh_util.SSH object at 0x7f45d95b1d90>, '_ssh_private_key_file': None, 'new_toplevel': None, '_conn': None, '_created_event': <threading.Event object at 0x7f45d9570b50>, '_errored': False}

Getting encrypted links defn of: {'_wait_for': [], 'depl': <nixops.deployment.Deployment object at 0x7f45dc69a0d0>, 'name': 'machineDemo2', 'id': 1168, 'logger': <nixops.logger.MachineLogger object at 0x7f45d95bc6d0>, 'defn': None, '_ssh_pinged_this_time': False, 'ssh': <nixops.ssh_util.SSH object at 0x7f45d95b1d90>, '_ssh_private_key_file': None, 'new_toplevel': None, '_conn': None, '_created_event': <threading.Event object at 0x7f45d9570b50>, '_errored': False}
Traceback (most recent call last):

  File "/home/jlotoski/.cache/pypoetry/virtualenvs/nixopsenv-Mqa0c7IS-py3.8/bin/nixops", line 11, in <module>
    load_entry_point('nixops', 'console_scripts', 'nixops')()
  File "/home/jlotoski/work/nixos/nixops-wt/nixops/nixops/__main__.py", line 710, in main
    args.op(args)
  File "/home/jlotoski/work/nixos/nixops-wt/nixops/nixops/script_defs.py", line 617, in op_deploy
    depl.deploy(
  File "/home/jlotoski/work/nixos/nixops-wt/nixops/nixops/deployment.py", line 1481, in deploy
    self.run_with_notify("deploy", lambda: self._deploy(**kwargs))
  File "/home/jlotoski/work/nixos/nixops-wt/nixops/nixops/deployment.py", line 1469, in run_with_notify
    f()
  File "/home/jlotoski/work/nixos/nixops-wt/nixops/nixops/deployment.py", line 1481, in <lambda>
    self.run_with_notify("deploy", lambda: self._deploy(**kwargs))
  File "/home/jlotoski/work/nixos/nixops-wt/nixops/nixops/deployment.py", line 1395, in _deploy
    self.configs_path = self.build_configs(
  File "/home/jlotoski/work/nixos/nixops-wt/nixops/nixops/deployment.py", line 826, in build_configs
    p = self.get_physical_spec()
  File "/home/jlotoski/work/nixos/nixops-wt/nixops/nixops/deployment.py", line 641, in get_physical_spec
    for name, attrs in DeploymentHooksManager.physical_spec(self).items():
  File "/home/jlotoski/work/nixos/nixops-wt/nixops/nixops/plugins/manager.py", line 22, in physical_spec
    for name, attrs in hook.physical_spec(deployment).items():
  File "/home/jlotoski/work/nix-community/nixops-encrypted-links-wt/nixops-encrypted-links/nixops_encrypted_links/plugin.py", line 21, in physical_spec
    return mk_matrix(d)
  File "/home/jlotoski/work/nix-community/nixops-encrypted-links-wt/nixops-encrypted-links/nixops_encrypted_links/lib.py", line 180, in mk_matrix
    do_machine(m)
  File "/home/jlotoski/work/nix-community/nixops-encrypted-links-wt/nixops-encrypted-links/nixops_encrypted_links/lib.py", line 103, in do_machine
    defn = to_encrypted_links_defn(m.defn)
  File "/home/jlotoski/work/nix-community/nixops-encrypted-links-wt/nixops-encrypted-links/nixops_encrypted_links/lib.py", line 72, in to_encrypted_links_defn
    raise TypeError('defn was None')
TypeError: defn was None
```

* Not sure yet if what needs to be fixed is in this repo or in the nixops-packet repo perhaps with machine destroy handling.

**Comment by johnalotoski** [comment]
* Addressed by PR https://github.com/nix-community/nixops-encrypted-links/pull/3 and nixops PR https://github.com/NixOS/nixops/pull/1430 which get the encypted-links plugin working in general.
* I think the above error may still be thrown in some edge cases when a machine gets created but doesn't receive a definition, perhaps because during machine creation the deployment failed part way through for other reasons.  In this edge case a machine destroy and re-deploy would seem to fix that, to ensure the machine gets a definition.  In any case, I'm not observing this error any more with the above mentioned PRs.
